# Generated by Django 2.1.2 on 2018-10-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181011_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
